#!/usr/bin/env python3
"""
Interview slide deck — thesis pipeline.

Launches a single-page slide deck for an interview session:

    python ui/app.py --project hibernate-orm --participant P01 --order ABC

The deck has 15 slides covering: title, preamble & consent, background, SonarQube
intro (if needed), Part 1 (current practice, Q1–Q3), Part 2 setup, Lists A/B/C,
compare view, Part 3 disclosure + reasoning card, Part 3 trust + adoption,
closing + post-interview notes.

Navigation: Prev/Next buttons or arrow keys.

The deck is purely presentational. No selections or responses are collected by
the UI — the interviewer takes notes externally. The Latin-square mapping is
applied so that List A/B/C show the alert tables for the correct underlying
condition (C1/C2/C3) per the --order argument.
"""
from __future__ import annotations

import argparse
import logging
from datetime import date
from pathlib import Path

import pandas as pd
import yaml
from flask import Flask, jsonify, render_template_string

BASE_DIR = Path(__file__).resolve().parent.parent
PROJECTS_DIR = BASE_DIR / "projects"
RESULTS_DIR = BASE_DIR / "results"

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s", datefmt="%H:%M:%S")
log = logging.getLogger(__name__)

# Latin-square mappings: visible-list-slot → underlying condition.
ORDER_MAP: dict[str, dict[str, str]] = {
    "ABC": {"A": "c1", "B": "c2", "C": "c3"},
    "ACB": {"A": "c1", "B": "c3", "C": "c2"},
    "BAC": {"A": "c2", "B": "c1", "C": "c3"},
    "BCA": {"A": "c2", "B": "c3", "C": "c1"},
    "CAB": {"A": "c3", "B": "c1", "C": "c2"},
    "CBA": {"A": "c3", "B": "c2", "C": "c1"},
}

# Display labels for condition disclosure (slide 11).
CONDITION_DESCRIPTIONS = {
    "c1": "A <strong>SonarQube-derived baseline</strong> ordering based on SonarQube severity information.",
    "c2": "Generated by a <strong>large language model</strong> using static alert information and file-level quality metrics from SonarQube.",
    "c3": "Generated by the <strong>same model</strong>, but it also received information about <strong>recent file changes</strong> and <strong>self-admitted technical debt</strong> comments in the source code.",
}

SESSION: dict = {}


def _load_display_set(results_path: Path, condition: str) -> list[dict]:
    path = results_path / f"display_set_{condition}.csv"
    if not path.exists():
        raise FileNotFoundError(f"{path} not found — run the display set builder first")
    df = pd.read_csv(path)
    df = df.where(pd.notna(df), None)
    return df.sort_values("rank").to_dict(orient="records")


def _load_project_config(project_id: str) -> dict:
    path = PROJECTS_DIR / f"{project_id}.yaml"
    if not path.exists():
        raise FileNotFoundError(f"Project config not found: {path}")
    return yaml.safe_load(path.read_text()) or {}


def _type_badge_class(t: str) -> str:
    t = (t or "").upper()
    if t == "BUG":
        return "badge-bug"
    if t == "VULNERABILITY":
        return "badge-vuln"
    return "badge-smell"


def _type_label(t: str) -> str:
    t = (t or "").upper()
    if t == "BUG":
        return "BUG"
    if t == "VULNERABILITY":
        return "VULN"
    return "SMELL"


def _sev_badge_class(s: str) -> str:
    s = (s or "").upper()
    if s == "HIGH":
        return "badge-high"
    if s == "MEDIUM":
        return "badge-medium"
    return "badge-low"


def _sev_label(s: str) -> str:
    s = (s or "").upper()
    if s == "HIGH":
        return "HIGH"
    if s == "MEDIUM":
        return "MED"
    return "LOW"


def _alert_for_view(a: dict) -> dict:
    line = a.get("line")
    try:
        line = int(float(line)) if line not in (None, "") else None
    except (ValueError, TypeError):
        line = None
    return {
        "rank": int(a.get("rank") or 0),
        "issue_key": str(a.get("issue_key") or ""),
        "file": str(a.get("file") or ""),
        "file_path": str(a.get("file_path") or ""),
        "rule": str(a.get("rule") or ""),
        "message": str(a.get("message") or ""),
        "line": line,
        "type": str(a.get("type") or ""),
        "effort": str(a.get("effort") or ""),
        "impact_severity": str(a.get("impact_severity") or "").upper(),
        "impact_quality": str(a.get("impact_quality") or "").upper(),
        "type_class": _type_badge_class(a.get("type")),
        "type_label": _type_label(a.get("type")),
        "sev_class": _sev_badge_class(a.get("impact_severity")),
        "sev_label": _sev_label(a.get("impact_severity")),
        "llm_reasoning": str(a.get("llm_reasoning") or ""),
    }


def initialize_session(project_id: str, participant_id: str, order: str) -> None:
    if order not in ORDER_MAP:
        raise ValueError(f"--order must be one of {sorted(ORDER_MAP)}")
    results_path = RESULTS_DIR / project_id
    if not results_path.exists():
        raise FileNotFoundError(f"Results directory not found: {results_path}")
    project_cfg = _load_project_config(project_id)
    mapping = ORDER_MAP[order]

    raw_sets = {c: _load_display_set(results_path, c) for c in ("c1", "c2", "c3")}
    visible = {label: [_alert_for_view(a) for a in raw_sets[mapping[label]]] for label in ("A", "B", "C")}

    # Build C3 rank-1 reasoning card payload.
    c3_top = [_alert_for_view(a) for a in raw_sets["c3"]][:1]
    c3_example = c3_top[0] if c3_top else None

    # Build disclosure ordering: list which visible label corresponds to each condition,
    # in C1 → C2 → C3 narrative order.
    reverse = {cond: label for label, cond in mapping.items()}
    disclosure_rows = [
        {"label": reverse["c1"], "text": CONDITION_DESCRIPTIONS["c1"]},
        {"label": reverse["c2"], "text": CONDITION_DESCRIPTIONS["c2"]},
        {"label": reverse["c3"], "text": CONDITION_DESCRIPTIONS["c3"]},
    ]

    SESSION.update({
        "project_id": project_id,
        "project_display_name": project_cfg.get("project_display_name", project_id),
        "participant_id": participant_id,
        "order": order,
        "condition_mapping": mapping,
        "date_today": date.today().isoformat(),
        "visible": visible,                # {"A": [...], "B": [...], "C": [...]}
        "c3_example": c3_example,
        "disclosure_rows": disclosure_rows,
    })
    log.info("Session ready: project=%s participant=%s order=%s mapping=%s",
             project_id, participant_id, order, mapping)


# ------------------------------------------------------------------ #
#  Slide-deck template (single page)                                   #
# ------------------------------------------------------------------ #

SLIDE_DECK = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Interview Slides — {{ project_display_name }}</title>
<style>
:root {
  --navy: #0f172a;
  --navy2: #1e293b;
  --navy3: #273548;
  --blue: #3b82f6;
  --blue-light: #60a5fa;
  --white: #f8fafc;
  --muted: #94a3b8;
  --border: #334155;
  --green: #4ade80;
  --red: #f87171;
  --amber: #fbbf24;
}
* { box-sizing: border-box; margin: 0; padding: 0; }
body {
  background: #111827;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  color: var(--white);
  padding: 20px;
}
.controls {
  display: flex; align-items: center; gap: 12px;
  margin-bottom: 16px; position: sticky; top: 0;
  background: #111827; padding: 10px 0; z-index: 100;
}
.controls button {
  background: var(--navy2); border: 1px solid var(--border);
  color: var(--white); padding: 8px 16px; border-radius: 6px;
  cursor: pointer; font-size: 13px;
}
.controls button:hover { background: var(--navy3); }
.controls button.active { background: var(--blue); border-color: var(--blue); }
.slide-counter { color: var(--muted); font-size: 13px; margin-left: auto; }

.slide {
  display: none;
  width: 100%; aspect-ratio: 16/9;
  background: var(--navy);
  border-radius: 12px;
  border: 1px solid var(--border);
  padding: 48px 56px;
  position: relative;
  overflow: hidden;
}
.slide.active { display: flex; flex-direction: column; }
.slide::before {
  content: ''; position: absolute; top: 0; right: 0;
  width: 200px; height: 4px;
  background: linear-gradient(90deg, transparent, var(--blue));
}
.slide::after {
  content: ''; position: absolute; top: 0; right: 0;
  width: 4px; height: 200px;
  background: linear-gradient(180deg, var(--blue), transparent);
}

.section-label {
  font-size: 11px; font-weight: 700; letter-spacing: 0.12em;
  text-transform: uppercase; color: var(--blue-light);
  margin-bottom: 20px;
}
h1 { font-size: 42px; font-weight: 700; line-height: 1.1; color: var(--white); margin-bottom: 12px; }
h2 { font-size: 26px; font-weight: 700; color: var(--white); margin-bottom: 20px; line-height: 1.2; }
h3 { font-size: 18px; font-weight: 600; color: var(--blue-light); margin-bottom: 10px; }
p, li { font-size: 16px; line-height: 1.6; color: #cbd5e1; }
ul { list-style: none; padding: 0; }
ul li { padding: 4px 0; padding-left: 16px; position: relative; }
ul li::before { content: '—'; position: absolute; left: 0; color: var(--blue); }

.q-block {
  background: var(--navy2); border: 1px solid var(--border);
  border-left: 3px solid var(--blue); border-radius: 8px;
  padding: 16px 20px; margin-bottom: 14px;
}
.q-label { font-size: 11px; font-weight: 700; color: var(--blue-light); letter-spacing: 0.08em; text-transform: uppercase; margin-bottom: 6px; }
.q-text { font-size: 17px; color: var(--white); line-height: 1.4; }
.probe { font-size: 13px; color: var(--muted); margin-top: 6px; font-style: italic; }

.title-slide { justify-content: center; }
.title-slide h1 { font-size: 48px; margin-bottom: 8px; }
.title-sub { font-size: 20px; color: var(--muted); margin-bottom: 40px; }
.title-meta { display: flex; gap: 32px; margin-top: 32px; }
.meta-field { background: var(--navy2); border: 1px solid var(--border); border-radius: 6px; padding: 10px 16px; }
.meta-label { font-size: 10px; color: var(--muted); text-transform: uppercase; letter-spacing: 0.1em; }
.meta-val { font-size: 14px; color: var(--white); margin-top: 2px; min-width: 120px; font-family: ui-monospace, monospace; }

.consent-box {
  background: var(--navy3); border: 1px solid var(--blue);
  border-radius: 8px; padding: 20px 24px; margin-top: 24px;
  display: flex; align-items: center; gap: 16px;
}
.consent-box p { font-size: 16px; color: var(--white); }
.checkbox-mock { width: 22px; height: 22px; border: 2px solid var(--blue); border-radius: 4px; flex-shrink: 0; }

.sq-diagram { display: flex; align-items: center; gap: 16px; margin-top: 24px; }
.sq-box { background: var(--navy2); border: 1px solid var(--border); border-radius: 8px; padding: 14px 20px; text-align: center; font-size: 14px; color: var(--white); font-weight: 600; }
.sq-arrow { font-size: 24px; color: var(--blue); }

.alert-table { width: 100%; border-collapse: collapse; font-size: 12px; }
.alert-table th {
  text-align: left; padding: 6px 8px;
  background: var(--navy3); color: var(--blue-light);
  font-size: 10px; text-transform: uppercase; letter-spacing: 0.08em;
  border-bottom: 1px solid var(--border);
}
.alert-table td { padding: 5px 8px; border-bottom: 1px solid rgba(51,65,85,0.5); color: #cbd5e1; vertical-align: middle; }
.alert-table tr:nth-child(even) td { background: rgba(30,41,59,0.4); }
.rank-num { font-family: ui-monospace, monospace; font-weight: 700; color: var(--blue-light); font-size: 13px; }
.badge { display: inline-block; padding: 1px 6px; border-radius: 3px; font-size: 9px; font-weight: 700; text-transform: uppercase; white-space: nowrap; }
.badge-bug { background: #4c1212; color: #fca5a5; border: 1px solid #ef4444; }
.badge-vuln { background: #4a1d6b; color: #d8b4fe; border: 1px solid #a855f7; }
.badge-smell { background: #1f2937; color: #cbd5e1; }
.badge-high { background: #7f1d1d; color: #fecaca; }
.badge-medium { background: #78350f; color: #fcd34d; }
.badge-low { background: #374151; color: #d1d5db; }
.file-name { font-family: ui-monospace, monospace; font-size: 11px; color: var(--muted); }
.msg-text { font-size: 11px; max-width: 360px; }
.effort-text { font-family: ui-monospace, monospace; font-size: 11px; color: var(--muted); }

.q-footer { margin-top: auto; padding-top: 16px; border-top: 1px solid var(--border); }
.q-footer .q-text { font-size: 15px; }

.compare-grid { display: grid; grid-template-columns: repeat(3,1fr); gap: 12px; flex: 1; min-height: 0; }
.compare-col { background: var(--navy2); border: 1px solid var(--border); border-radius: 8px; overflow: hidden; display: flex; flex-direction: column; min-height: 0; }
.compare-col-header { padding: 8px 12px; background: var(--navy3); border-bottom: 1px solid var(--border); font-size: 14px; font-weight: 700; color: var(--white); flex-shrink: 0; }
.compare-col-body { overflow-y: auto; flex: 1; }
.compare-row { padding: 5px 10px; border-bottom: 1px solid rgba(51,65,85,0.4); font-size: 10px; line-height: 1.4; }
.compare-rank { color: var(--blue-light); font-weight: 700; margin-right: 6px; font-family: ui-monospace, monospace; }
.compare-file { color: var(--muted); font-family: ui-monospace, monospace; }
.compare-msg { color: #cbd5e1; }

.reasoning-card {
  background: linear-gradient(135deg, var(--navy2), var(--navy3));
  border: 1px solid var(--blue); border-radius: 10px;
  padding: 24px 28px; flex: 1;
}
.rc-meta { font-size: 12px; color: var(--muted); margin-bottom: 16px; }
.rc-meta span { color: var(--white); }
.rc-quote {
  font-size: 16px; line-height: 1.7; color: var(--white);
  font-style: italic; border-left: 3px solid var(--blue); padding-left: 16px;
}

.disclosure-grid { display: flex; flex-direction: column; gap: 10px; flex: 1; }
.disc-item {
  background: var(--navy2); border: 1px solid var(--border);
  border-left: 3px solid var(--blue); border-radius: 6px;
  padding: 12px 16px; display: flex; gap: 14px; align-items: flex-start;
}
.disc-label { font-size: 13px; font-weight: 700; color: var(--blue-light); white-space: nowrap; padding-top: 1px; min-width: 60px; font-family: ui-monospace, monospace; }
.disc-text { font-size: 14px; color: #cbd5e1; line-height: 1.5; }

.closing-quote {
  font-size: 22px; color: var(--white); line-height: 1.6;
  font-style: italic; border-left: 3px solid var(--blue);
  padding-left: 24px; margin: 24px 0;
}
</style>
</head>
<body>

<div class="controls">
  <button onclick="prev()">← Prev</button>
  <button onclick="next()">Next →</button>
  <span class="slide-counter" id="counter">1 / 15</span>
</div>

<!-- SLIDE 1: TITLE -->
<div class="slide title-slide active" id="s1">
  <div class="section-label">Study · Schuberg Philis · 2026</div>
  <h1>LLM-Based Alert<br>Prioritisation Study</h1>
  <div class="title-sub">Interview Session — {{ project_display_name }}</div>
  <div class="title-meta">
    <div class="meta-field">
      <div class="meta-label">Participant ID</div>
      <div class="meta-val">{{ participant_id }}</div>
    </div>
    <div class="meta-field">
      <div class="meta-label">Date</div>
      <div class="meta-val">{{ date_today }}</div>
    </div>
    <div class="meta-field">
      <div class="meta-label">List Order</div>
      <div class="meta-val">{{ order }}</div>
    </div>
  </div>
</div>

<!-- SLIDE 2: PREAMBLE -->
<div class="slide" id="s2">
  <div class="section-label">Opening · Preamble & Consent</div>
  <h2>Welcome</h2>
  <p style="font-size:17px;color:#e2e8f0;line-height:1.8;margin-bottom:20px;">
    "Thank you for participating. I am studying how developers evaluate and prioritise static analysis alerts. I will show you three ranked lists of alerts and ask for your reactions.<br><br>
    There are no right or wrong answers — I am interested in your professional judgement. Your responses will be anonymised and you may stop at any time."
  </p>
  <div class="consent-box">
    <div class="checkbox-mock"></div>
    <p>Do I have your consent to record this interview for transcription and analysis?</p>
  </div>
</div>

<!-- SLIDE 3: BACKGROUND -->
<div class="slide" id="s3">
  <div class="section-label">Part 0 · Background</div>
  <h2>Background Questions</h2>
  <div class="q-block">
    <div class="q-label">B1</div>
    <div class="q-text">How many years of software engineering experience do you have in total, and how long have you been at Schuberg Philis?</div>
  </div>
  <div class="q-block">
    <div class="q-label">B2</div>
    <div class="q-text">What kind of systems do you currently work on?</div>
  </div>
  <div class="q-block">
    <div class="q-label">B3</div>
    <div class="q-text">How familiar are you with static analysis tools such as SonarQube, ESLint, CodeQL, or similar?</div>
  </div>
</div>

<!-- SLIDE 4: SONARQUBE INTRO -->
<div class="slide" id="s4">
  <div class="section-label">Context · SonarQube Overview</div>
  <h2>What is SonarQube?</h2>
  <p style="margin-bottom:16px;">SonarQube is a widely used static code analysis tool. It scans source code and produces a list of alerts — issues it detects such as bugs, security vulnerabilities, and code quality problems.</p>
  <ul style="margin-bottom:20px;">
    <li><strong style="color:var(--white)">Type</strong> — Bug, Vulnerability, or Code Smell</li>
    <li><strong style="color:var(--white)">Severity</strong> — High, Medium, or Low</li>
    <li><strong style="color:var(--white)">File and line</strong> where the issue was found</li>
    <li><strong style="color:var(--white)">Estimated effort</strong> to fix it</li>
  </ul>
  <div class="sq-diagram">
    <div class="sq-box">Source Code</div>
    <div class="sq-arrow">→</div>
    <div class="sq-box">SonarQube<br>Analysis</div>
    <div class="sq-arrow">→</div>
    <div class="sq-box">Alert List<br>(ranked)</div>
  </div>
</div>

<!-- SLIDE 5: PART 1 Q1-Q3 -->
<div class="slide" id="s5">
  <div class="section-label">Part 1 · Current Practice · RQ1</div>
  <h2>How do you work with static analysis today?</h2>
  <div class="q-block">
    <div class="q-label">Q1</div>
    <div class="q-text">Do you use static analysis tools in your work — things like SonarQube, ESLint, or similar? Why or why not?</div>
  </div>
  <div class="q-block">
    <div class="q-label">Q2</div>
    <div class="q-text">When you see many alerts, how do you decide what to fix first?</div>
  </div>
  <div class="q-block">
    <div class="q-label">Q3</div>
    <div class="q-text">What makes an alert worth fixing immediately versus ignoring or deferring?</div>
  </div>
</div>

<!-- SLIDE 6: PART 2 SETUP -->
<div class="slide" id="s6">
  <div class="section-label">Part 2 · Ranking Evaluation · RQ2</div>
  <h2>Three ranked lists</h2>
  <p style="font-size:17px;color:#e2e8f0;line-height:1.8;">
    "I am going to show you three ranked lists of alerts from the same real open-source Java repository — <strong style="color:var(--white)">{{ project_display_name }}</strong>.<br><br>
    Each list was generated from the same underlying candidate pool of alerts. You will see the top-ranked alerts produced by each list, so the lists may overlap but may not contain exactly the same alerts.<br><br>
    The lists are labelled <strong style="color:var(--blue-light)">A</strong>, <strong style="color:var(--blue-light)">B</strong>, and <strong style="color:var(--blue-light)">C</strong>. I will explain how they were produced after you have evaluated them."
  </p>
  <div style="margin-top:24px;background:var(--navy2);border:1px solid var(--blue);border-radius:8px;padding:14px 18px;">
    <p style="color:var(--blue-light);font-size:14px;font-weight:600;">For each list: scan it, then I will ask one question.</p>
  </div>
</div>

{% for label in ['A','B','C'] %}
<div class="slide" id="s{{ 6 + loop.index }}" style="padding:32px 40px;">
  <div class="section-label">Part 2 · List {{ label }} &nbsp;|&nbsp; <span style="color:var(--muted);font-weight:400;">{{ project_display_name }} · {{ visible[label]|length }} alerts</span></div>
  <table class="alert-table">
    <thead>
      <tr><th>#</th><th>Type</th><th>Sev</th><th>File</th><th>Message</th><th>Effort</th></tr>
    </thead>
    <tbody>
      {% for a in visible[label] %}
      <tr>
        <td class="rank-num">{{ a.rank }}</td>
        <td><span class="badge {{ a.type_class }}">{{ a.type_label }}</span></td>
        <td><span class="badge {{ a.sev_class }}">{{ a.sev_label }}</span></td>
        <td class="file-name">{{ a.file }}</td>
        <td class="msg-text">{{ a.message }}</td>
        <td class="effort-text">{{ a.effort }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <div class="q-footer">
    <div class="q-label">Q4</div>
    <div class="q-text">What stands out at the top? Anything you would investigate first, skip, or move lower?</div>
  </div>
</div>
{% endfor %}

<!-- SLIDE 10: COMPARE -->
<div class="slide" id="s10" style="padding:28px 36px;">
  <div class="section-label">Part 2 · Side-by-Side Comparison</div>
  <div class="compare-grid" style="margin-bottom:14px;">
    {% for label in ['A','B','C'] %}
    <div class="compare-col">
      <div class="compare-col-header">List {{ label }}</div>
      <div class="compare-col-body">
        {% for a in visible[label] %}
        <div class="compare-row">
          <span class="compare-rank">{{ a.rank }}.</span><span class="compare-file">{{ a.file }}</span> — <span class="compare-msg">{{ a.message[:80] }}{% if a.message|length > 80 %}…{% endif %}</span>
        </div>
        {% endfor %}
      </div>
    </div>
    {% endfor %}
  </div>
  <div style="background:var(--navy2);border:1px solid var(--border);border-radius:8px;padding:12px 16px;">
    <span style="color:var(--blue-light);font-weight:700;font-size:13px;">Q5</span> <span style="font-size:14px;"> Which list would you most want to work from today, and why?</span> &nbsp;&nbsp;
    <span style="color:var(--blue-light);font-weight:700;font-size:13px;">Q6</span> <span style="font-size:14px;"> Which would you find least useful, and why?</span> &nbsp;&nbsp;
    <span style="color:var(--blue-light);font-weight:700;font-size:13px;">Q7</span> <span style="font-size:14px;"> Did the ordering itself make one feel more or less actionable?</span>
  </div>
</div>

<!-- SLIDE 11: DISCLOSURE -->
<div class="slide" id="s11">
  <div class="section-label">Part 3 · Disclosure · RQ3</div>
  <h2>How each list was produced</h2>
  <p style="margin-bottom:20px;color:var(--muted);">"I can now tell you how each list was produced."</p>
  <div class="disclosure-grid">
    {% for row in disclosure_rows %}
    <div class="disc-item">
      <div class="disc-label">List {{ row.label }}</div>
      <div class="disc-text">{{ row.text | safe }}</div>
    </div>
    {% endfor %}
  </div>
  <p style="margin-top:20px;color:var(--muted);font-style:italic;">Give the participant time to process.</p>
</div>

<!-- SLIDE 12: Q8-Q9 -->
<div class="slide" id="s12">
  <div class="section-label">Part 3 · Trust · RQ3</div>
  <h2>Reactions to disclosure</h2>
  <div class="q-block">
    <div class="q-label">Q8</div>
    <div class="q-text">Does knowing this change your preference, or your view of any of the lists?</div>
  </div>
  <div class="q-block">
    <div class="q-label">Q9</div>
    <div class="q-text">Does it concern you that two of these lists were generated by an LLM? Why or why not?</div>
    <div class="probe">Probe if short: Is there a past experience that shapes this view?</div>
  </div>
</div>

<!-- SLIDE 13: REASONING CARD -->
<div class="slide" id="s13">
  <div class="section-label">Part 3 · Reasoning Card · RQ3</div>
  <h2>Example: LLM reasoning for List C (rank 1)</h2>
  {% if c3_example %}
  <div class="reasoning-card">
    <div class="rc-meta">
      <span style="color:var(--blue-light);">Rule:</span> <span>{{ c3_example.rule }}</span> &nbsp;·&nbsp;
      <span style="color:var(--blue-light);">File:</span> <span>{{ c3_example.file }}</span>{% if c3_example.line %} &nbsp;·&nbsp; <span style="color:var(--blue-light);">Line:</span> <span>{{ c3_example.line }}</span>{% endif %}<br><br>
      <span style="color:var(--blue-light);">Alert:</span> <span>{{ c3_example.message }}</span>
    </div>
    <div class="rc-quote">"{{ c3_example.llm_reasoning }}"</div>
  </div>
  {% else %}
  <p style="color:var(--red);">No C3 reasoning available — display_set_c3.csv is empty.</p>
  {% endif %}
  <div class="q-footer">
    <div class="q-label">Q10</div>
    <div class="q-text">What is your reaction to this reasoning? Does seeing it make you more trusting, less trusting, or does it not change your view?</div>
  </div>
</div>

<!-- SLIDE 14: Q11-Q12 -->
<div class="slide" id="s14">
  <div class="section-label">Part 3 · Adoption · RQ3</div>
  <h2>Usefulness and future design</h2>
  <div class="q-block">
    <div class="q-label">Q11</div>
    <div class="q-text">If an LLM-assisted static analysis alert prioritisation tool were available to your team, would it be useful? What would need to be true for you or your team to rely on it in practice?</div>
  </div>
  <div class="q-block">
    <div class="q-label">Q12</div>
    <div class="q-text">If you could design the ideal tool for this problem, what would it look like?</div>
    <div class="probe">Probe: Would you trust full AI prioritisation, or do you need the static analysis foundation underneath it?</div>
  </div>
</div>

<!-- SLIDE 15: CLOSING -->
<div class="slide" id="s15">
  <div class="section-label">Closing</div>
  <h2>Thank you</h2>
  <div class="closing-quote">
    "That is everything. Is there anything else that you would like to add?"
  </div>
  <p style="font-size:16px;color:#e2e8f0;margin-bottom:12px;">
    "Thank you for participating — your responses will be anonymised in the thesis."
  </p>
  <div style="margin-top:32px;background:var(--navy2);border:1px solid var(--border);border-radius:8px;padding:20px 24px;">
    <p style="font-size:13px;color:var(--muted);font-weight:700;text-transform:uppercase;letter-spacing:0.08em;margin-bottom:12px;">Post-interview notes (complete within 30 minutes)</p>
    <div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;font-size:13px;color:var(--muted);">
      <div>Static analysis experience: Daily / Weekly / Occasional / Rare / Never</div>
      <div>Repository familiarity: High / Moderate / Low / None</div>
      <div>Alert fatigue mentioned spontaneously: Yes / No</div>
      <div>Preference before disclosure: List ___</div>
      <div>Preference changed after disclosure: Yes / No / Partially</div>
      <div>Reasoning card reaction: Positive / Skeptical / Neutral / Mixed</div>
    </div>
  </div>
</div>

<script>
const slides = document.querySelectorAll('.slide');
let cur = 0;
const total = slides.length;
function show(n){
  slides[cur].classList.remove('active');
  cur = (n + total) % total;
  slides[cur].classList.add('active');
  document.getElementById('counter').textContent = (cur+1) + ' / ' + total;
}
function next(){ show(cur+1); }
function prev(){ show(cur-1); }
document.addEventListener('keydown', e => {
  if (e.key === 'ArrowRight' || e.key === 'ArrowDown' || e.key === ' ') { e.preventDefault(); next(); }
  if (e.key === 'ArrowLeft' || e.key === 'ArrowUp') { e.preventDefault(); prev(); }
});
</script>
</body>
</html>"""


# ------------------------------------------------------------------ #
#  Flask app                                                           #
# ------------------------------------------------------------------ #

app = Flask(__name__)


@app.route("/")
def index():
    return render_template_string(SLIDE_DECK, **SESSION)


@app.route("/health")
def health():
    return jsonify({"status": "ok"})


def main() -> None:
    parser = argparse.ArgumentParser(description="Interview slide deck — single-participant session.")
    parser.add_argument("--project", required=True, help="Project ID (matches results/<id>/)")
    parser.add_argument("--participant", required=True, help="Participant ID, e.g. P01")
    parser.add_argument("--order", required=True, choices=sorted(ORDER_MAP.keys()),
                        help="Latin-square ordering (ABC, ACB, BAC, BCA, CAB, CBA)")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=5001)
    args = parser.parse_args()

    initialize_session(args.project, args.participant, args.order)
    log.info("Launching on http://%s:%d", args.host, args.port)
    app.run(host=args.host, port=args.port, debug=False)


if __name__ == "__main__":
    main()
